# Generated by Django 2.0.7 on 2018-08-01 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_id', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='ImageClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_number', models.IntegerField()),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='app.Image')),
            ],
        ),
        migrations.AddIndex(
            model_name='imageclass',
            index=models.Index(fields=['class_number'], name='app_imagecl_class_n_6025fe_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='imageclass',
            unique_together={('image', 'class_number')},
        ),
    ]
